.label zpLow                   	= $02
.label zpHigh                  	= $03
.label zpScnPtrLo              	= $04
.label zpScnPtrHi              	= $05
.label zpColPtrLo              	= $06
.label zpColPtrHi              	= $07
.label currentLevel            	= $08
.label charColour              	= $09
.label charCode                	= $0A
.label charLength              	= $0B
.label zpDataPtrLo             	= $0C
.label zpDataPtrHi             	= $0D
.label minerX                  	= $0E
.label minerY                  	= $0F
.label minerXMSB               	= $10
.label enemyX                  	= $11
.label enemyY                  	= $12

.label minerDirection          	= $14
.label minerAnimCounter        	= $15
.label playerInput             	= $16
.label jumpEnable              	= $17
.label jumpCounter             	= $18
.label jumpDelay               	= $19
.label charSelected            	= $1A
.label offset                  	= $1B
.label fallEnable              	= $1C
.label loseLifeFlag            	= $1D
.label lives                   	= $1E
.label air                     	= $1F
.label airCounter              	= $20
.label platformDirection       	= $21
.label onPlatform              	= $22
.label keysLeft                	= $23
.label minerChangeDirection    	= $24
.label minerFrame              	= $25
.label minerMove               	= $26
.label enemyStartX		= $27
.label enemyStartY		= $28
.label enemyEnd			= $29
.label enemyDirection		= $2A
.label enemyCounter		= $2B
.label enemyAnimCounter		= $2C
.label enemyFrame		= $2D
.label exitColPtr              	= $2E //to $2F
.label keyColPtr               	= $30 //to $39
.label keyColour               	= $3A
.label row                     	= $3B
.label col                     	= $3C
.label gameFlag                 = $3D
.label gameStatus              	= $3E
.label zpTemp                  	= $3F
.label collision               	= $40
.label score			= $41 //to $45
.label fallCounter		= $46

